eeglib

In [10]:
import pandas as pd
df = pd.read_csv("data/115/001_EEG_baseline_stroke_study_updated.csv")


In [11]:
df.head()

timestamps     TP9     AF7      AF8    TP10  Right AUX  Marker0
0  1.483586e+09  23.926  11.719  121.094  22.949     42.969        0
1  1.483586e+09  22.461  39.062   -9.277  24.414     29.785        0
2  1.483586e+09  23.926  37.109  -19.531  23.926     17.090        0
3  1.483586e+09  38.574  28.809   47.363  41.992     18.066        0
4  1.483586e+09  52.734  66.895   51.758  57.617     10.742        0

In [12]:
# Remove your last columns
df.drop(df.columns[[-1, -2]],axis=1,inplace=True)

In [14]:
# Remove your first column
df.drop(df.columns[0], axis=1, inplace=True)

In [15]:
df.head()

TP9     AF7      AF8    TP10
0  23.926  11.719  121.094  22.949
1  22.461  39.062   -9.277  24.414
2  23.926  37.109  -19.531  23.926
3  38.574  28.809   47.363  41.992
4  52.734  66.895   51.758  57.617

In [16]:
df.to_csv("data/feature_processing/001_EEG_baseline_stroke_study_updated.csv", index=False)

In [35]:
import eeglib as eeg	
helper = eeg.helpers.CSVHelper("data/feature_processing/001_EEG_baseline_stroke_study_updated.csv", lowpass=30, highpass=0.5, normalize=True, ICA=True, windowSize=128)



In [36]:
wrap = eeg.wrapper.Wrapper(helper)



In [37]:
for egg in helper:
    print(egg.PFD())

[1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1.]
[1.         1.         1.         1.         1.         1.
 1.00064347]
[1.00064347 1.         1.         1.         1.00064347 1.00064347
 1.        ]
[1.         1.00064347 1.         1.         1.         1.
 1.        ]
[1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1.]
[1.         1.         1.00064347 1.00064347 1.00064347 1.
 1.00064347]
[1.00064347 1.         1.         1.         1.         1.00064347
 1.        ]
[1. 1. 1. 1. 1. 1. 1.]
[1.         1.00064347 1.         1.         1.         1.
 1.        ]
[1. 1. 1. 1. 1. 1. 1.]
[1.         1.         1.         1.         1.         1.
 1.00064347]
[1.00064347 1.         1.         1.         1.         1.
 1.        ]
[1.         1.         1.         1.         1.         1.00064347
 1.        ]
[1.         1.00064347 1.00064347 1.         1.00064347 1.
 1.00064347]
[1.         1.         1.         1.         1.         1.
 1.00064347]


In [38]:

wrap.addFeature.HFD()




In [39]:
wrap.addFeature.DFA()

In [40]:
features = wrap.getFeatures()

In [41]:
features

HFD(){}_0      1.044228
HFD(){}_1      1.227505
HFD(){}_2      1.083590
HFD(){}_3      1.081786
HFD(){}_4      1.105413
HFD(){}_5      1.090983
HFD(){}_6      1.082012
DFA(){}_0      2.092375
DFA(){}_1      2.081771
DFA(){}_2      2.089766
DFA(){}_3      2.089046
DFA(){}_4      2.083383
DFA(){}_5      2.087689
DFA(){}_6      2.089566
window_id    393.000000
dtype: float64

HFD(){}_0      1.088085
HFD(){}_1      1.078684
HFD(){}_2      1.267013
HFD(){}_3      1.084084
DFA(){}_0      2.087306
DFA(){}_1      2.089664
DFA(){}_2      2.067421
DFA(){}_3      2.089045
window_id    393.000000



In [26]:
type(features)

pandas.core.series.Series

In [28]:
import numpy as np
tiny = list(features)

In [31]:
tiny.pop()

393.0

In [32]:
new_df = pd.DataFrame(columns=("HFD0", "HFD1", "HFD2", "HFD3", "DFA0", "DFA1", "DFA2", "DFA3"))

In [33]:
new_df.loc[0] = tiny

In [34]:
new_df.head()

HFD0      HFD1      HFD2      HFD3      DFA0      DFA1      DFA2  \
0  1.088085  1.078684  1.267013  1.084084  2.087306  2.089664  2.067421   

       DFA3  
0  2.089045